---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hw
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: hw
  chart:
    repository: https://sel-vcc.github.io/helm-charts/
    name: hw
    version: 0.1.1
  values:
    image:
      repository: slarkin/hw
      tag: 0.2.0
